import NavBar from "@/components/navbar/navbar";
import "./globals.scss";
import type { Metadata } from "next";
import { IBM_Plex_Mono, Silkscreen } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
